
# MySQL
spring:
  datasource:
    hikari:
      connection-test-query : SELECT NOW() FROM dual
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    check-template-location: true

# mybatis
mybatis:
  configuration:
    cache-enabled : false
    jdbc-type-for-null : NULL
    map-underscore-to-camel-case : true
